name: deploy-config
on:
  workflow_dispatch:
env:
  node-version: "16.x"
  environment: "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
      - name: Build
        run: node index.js
        env:
          environment: ${{ env.environment }}
      - uses: actions/checkout@v2
      - name: Copy files
        uses: ulaval/azure-blob-copy-action@v1
        with:
          action: upload
          connection_string: ${{ secrets.CONNECTION_STRING }}
          container_name: "aditya-test"
          local_directory: "config_dev"
          blob_directory: "."
          http_headers: |
            - glob: "**/*.????????.*"
              headers:
                Cache-Control: public, max-age=604800, immutable

            - glob: "**.*"
              headers:
                Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate
