name: deploy-config
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag name'
        required: true
        type: string
env:
  node-version: "16.x"
  environment: "DEVELOPMENT"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $TAGS" 
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ inputs.tags }}
          message: "Latest release"
      - name: Install dependencies
        run: npm install 
      - name: Build
        run: node index.js
        env:
          environment: ${{ env.environment }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - name: Lint
        run: npm run lint
      - name: Copy files
        uses: ulaval/azure-blob-copy-action@v1
        with:
          action: upload
          connection_string: ${{ secrets.CONNECTION_STRING }}
          container_name: "aditya-test"
          local_directory: "config"
          blob_directory: "."
          http_headers: |
            - glob: "**/*.????????.*"
              headers:
                Cache-Control: public, max-age=604800, immutable
            - glob: "**.*"
              headers:
                Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate
